
import 'package:forms/models/article.dart';

class DummyArticleProvider{
  static List<Article> getDummyArticle(){
    return [
      Article(1, "Scientists Used Yellowstone Hot Springs to Study the Moment That Kickstarted Life on Earth", "A new study highlights how life possibly evolved prior to and during the rise of Earth’s oxygenated atmosphere.", """Some 2.4 billion years ago, the Earth’s atmosphere underwent a rapid increase in oxygen levels known as the Great Oxidation Event (GOE).
A new study analyzes thermophilic microbe communities in two springs in Yellowstone National Park that represent snapshots of the Earth before and after the GOE.
This research shows how increased oxygenation supported more diversity and how organisms in more anoxic conditions scraped by in a pre-GOE environment.
Attracting nearly five million visitors every year, Yellowstone National Park is one of the world’s most wondrous collections of geysers, hot springs, mud pots, and fumaroles—all powered by a large underground magma chamber. Although the Old Faithful geyser is often the star of the show (and, potentially, the cause of our future destruction), many other geologic formations and hot springs within the famous park contain a host of information vital for scientists trying to understand how ancient life evolved on Earth.""", "Darren Orf", "Feb 14, 2025 9:30 AM EST", "https://hips.hearstapps.com/hmg-prod/images/grand-prismatic-spring-yellowstones-largest-hot-spring-is-news-photo-1739483779.pjpeg?crop=0.6582xw:1xh;center,top&resize=640:*"),
      Article(2, "Scientists Used Yellowstone Hot Springs to Study the Moment That Kickstarted Life on Earth", "A new study highlights how life possibly evolved prior to and during the rise of Earth’s oxygenated atmosphere.", """Some 2.4 billion years ago, the Earth’s atmosphere underwent a rapid increase in oxygen levels known as the Great Oxidation Event (GOE).
A new study analyzes thermophilic microbe communities in two springs in Yellowstone National Park that represent snapshots of the Earth before and after the GOE.
This research shows how increased oxygenation supported more diversity and how organisms in more anoxic conditions scraped by in a pre-GOE environment.
Attracting nearly five million visitors every year, Yellowstone National Park is one of the world’s most wondrous collections of geysers, hot springs, mud pots, and fumaroles—all powered by a large underground magma chamber. Although the Old Faithful geyser is often the star of the show (and, potentially, the cause of our future destruction), many other geologic formations and hot springs within the famous park contain a host of information vital for scientists trying to understand how ancient life evolved on Earth.""", "Darren Orf", "Feb 14, 2025 9:30 AM EST", "https://hips.hearstapps.com/hmg-prod/images/grand-prismatic-spring-yellowstones-largest-hot-spring-is-news-photo-1739483779.pjpeg?crop=0.6582xw:1xh;center,top&resize=640:*"),
      Article(3, "Scientists Used Yellowstone Hot Springs to Study the Moment That Kickstarted Life on Earth", "A new study highlights how life possibly evolved prior to and during the rise of Earth’s oxygenated atmosphere.", """Some 2.4 billion years ago, the Earth’s atmosphere underwent a rapid increase in oxygen levels known as the Great Oxidation Event (GOE).
A new study analyzes thermophilic microbe communities in two springs in Yellowstone National Park that represent snapshots of the Earth before and after the GOE.
This research shows how increased oxygenation supported more diversity and how organisms in more anoxic conditions scraped by in a pre-GOE environment.
Attracting nearly five million visitors every year, Yellowstone National Park is one of the world’s most wondrous collections of geysers, hot springs, mud pots, and fumaroles—all powered by a large underground magma chamber. Although the Old Faithful geyser is often the star of the show (and, potentially, the cause of our future destruction), many other geologic formations and hot springs within the famous park contain a host of information vital for scientists trying to understand how ancient life evolved on Earth.""", "Darren Orf", "Feb 14, 2025 9:30 AM EST", "https://hips.hearstapps.com/hmg-prod/images/grand-prismatic-spring-yellowstones-largest-hot-spring-is-news-photo-1739483779.pjpeg?crop=0.6582xw:1xh;center,top&resize=640:*")
    ];
  }
}